### ISSUE TITLE
Oxigraph Store

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/idpd-api-poc#126]
## Oxigraph Store

_This is moving beyond using the stub and implementing the OxigraphMetadataStore methods so that we can power the api directly using a graph database._

- [ ] [(re) implement `OxigraphMetadataStore.get_dataset({id})` methods to power the `/datasets/{id{}` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/22)
- [ ] [implement `OxigraphMetadataStore.get_datasets()` methods to power the `/datasets/` endpoint with data from the graph. Write test.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/39).
- [ ] [implement `OxigraphMetadataStore.get_edition({id})` methods to power the `/datasets/{id}/edition/{id}` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/56)
- [ ] [implement `OxigraphMetadataStore.get_editions()` methods to power the `/datasets/{id}/editions` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/57)
- [ ] [implement `OxigraphMetadataStore.get_version({id})` methods to power the `/datasets/{id}/editions/{id}/versions/{id}` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/58)
- [ ] [implement `OxigraphMetadataStore.get_versions()` methods to power the `/datasets/{id}/editions/{id}/versions` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/70)
- [ ] [implement `OxigraphMetadataStore.get_publisher({id})` methods to power the `/publisher/{id}/` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/71)
- [ ] [implement `OxigraphMetadataStore.get_publishers()` methods to power the `/publisher` endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/72)
- [ ] [implement `OxigraphMetadataStore.get_topic({id})` methods to power the `/topics/{id}/`endpoint with data from the graph. Write tests.](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gh/gss-cogs/idpd-api-poc/73)
- [ ] [implement `OxigraphMetadataStore.get_topics()` methods to power the `/topics` endpoint with data from the graph. Write tests.](https://github.com/GSS-Cogs/idpd-api-poc/issues/74)
